name: JSON File Validation
on:
  pull_request_target:
    branches: [ main ]
    paths:
      - 'languages/**/*.json'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get changed files
        id: changed-files
        uses: actions/github-script@v7
        with:
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const jsonFiles = files
              .filter(file => 
                file.status !== 'removed' && 
                file.filename.endsWith('.json')
              )
              .map(file => file.filename);
            
            console.log('All changed files:', files.map(f => f.filename));
            console.log('JSON files to validate:', jsonFiles);
            
            core.setOutput('files', jsonFiles.join('\n'));
            core.exportVariable('CHANGED_FILES', jsonFiles.join('\n'));
            core.setOutput('json_file_count', jsonFiles.length);

      - name: Skip if no JSON files changed
        if: steps.changed-files.outputs.json_file_count == 0
        run: |
          echo "No JSON files were modified in this PR"
          exit 0

      - name: Create validation script directory
        run: mkdir -p scripts

      - name: Copy validation script
        run: |
          cat > scripts/validate_json.py << 'EOF'
          # Content of the Python validator script will be inserted here
          EOF

      - name: Validate JSON files
        id: validation
        run: |
          echo "Changed JSON files to validate: $CHANGED_FILES"
          if python scripts/validate_json.py; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
            echo "::error::JSON validation failed"
            exit 1
          fi

      - name: Create PR Comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## JSON Validation Results\n\n';
            
            try {
              const results = JSON.parse(fs.readFileSync('validation-results.json', 'utf8'));
              const summary = results.summary;
              
              if (summary.total === 0) {
                comment += '⚠️ No JSON files were found in this PR for validation.\n';
              } else {
                // Add summary section
                comment += `### Summary\n`;
                comment += `- Total files validated: ${summary.total}\n`;
                comment += `- ✅ Passed: ${summary.passed}\n`;
                comment += `- ❌ Failed: ${summary.failed}\n\n`;
                
                // Add detailed results
                if (summary.failed > 0) {
                  comment += `### Detailed Results\n\n`;
                  for (const result of results.results) {
                    if (result.success) {
                      comment += `#### ✅ \`${result.file}\`\n`;
                      comment += 'JSON syntax validation passed successfully.\n\n';
                    } else {
                      comment += `#### ❌ \`${result.file}\`\n`;
                      comment += 'The following issues were found:\n';
                      result.errors.forEach(error => {
                        comment += `- ${error}\n`;
                      });
                      comment += '\n';
                    }
                  }
                }
              }
            } catch (error) {
              comment += '⚠️ Error occurred while loading validation results.\n';
              comment += `Error details: ${error.message}\n`;
            }
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Check validation result
        if: steps.validation.outputs.status == 'failure'
        run: |
          echo "Validation failed"
          exit 1