name: Update Version Metadata

on:
  push:
    branches: [ main ]
    paths:
      - 'languages/**'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate version metadata
        run: |
          python scripts/generate_versions.py
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(versions): update version metadata [skip ci]"
          file_pattern: 'versions.json'
          commit_author: GitHub Action <actions@github.com>   