name: Update Version Metadata

on:
  push:
    branches: [ main ]
    paths:
      - 'languages/**'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate version metadata
        run: |
          python scripts/generate_versions.py